routes/web.php
<?php

use App\Http\Controllers\ResultsController;
use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/**
 * ADMIN ROUTES
 */
Route::middleware(['verifyAdmin'])->group(function(){

    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('dashboard');
    Route::get('/cpanel/users', 'admin\UsersController@index')->name('users.index');


// Route::get('/cpanel/subject.chapter','admin\ChaptersController')->except(['index','show']);

    //new changes
    Route::get('/cpanel/chapters/create', 'admin\ChaptersController@createChapter')->name('createChapter');
    Route::get('/cpanel/chapters', 'admin\ChaptersController@indexChapter')->name('indexChapter');
    //end of new changes

    Route::resource('/cpanel/subject.chapters','admin\ChaptersController')->except(['edit','update','destroy']);
    Route::get('/cpanel/chapter/{chapter}/edit','admin\ChaptersController@editChapter')->name('chapter.editChapter');
    Route::put('/cpanel/chapter/{chapter}/update','admin\ChaptersController@updateChapter')->name('chapter.updateChapter');
    Route::delete('/cpanel/chapter/{chapter}/delete','admin\ChaptersController@destroyChapter')->name('chapter.destroyChapter');

    /**
     * QUESTIONS
     */
    Route::resource('/cpanel/chapter.questions', 'admin\QuestionsController');
    Route::get('/cpanel/chapters/{chapter}/questions/create','admin\QuestionsController@createQuestion')->name('questions.createQuestion');
    Route::get('/cpanel/chapters/{chapter}/questions/{question}/edit','admin\QuestionsController@editQuestion')->name('questions.editQuestion');
    /**
     * END OF QUESTIONS
     */

    /**
     * SUBJECTS
     */
    Route::resource('/cpanel/subjects','admin\SubjectsController');

    Route::resource('/cpanel/subjects.tests','admin\TestsController')->except(['edit','update','destroy']);
    /**
     * END OF SUBJECTS
     */

    Route::get('/cpanel/quiz/{test}/result','admin\ResultsController@getResult')->name('test.result');

});

/**
 * STUDENT ROUTES
 */
Route::middleware(['auth','verifyStudent'])->group(function(){

    Route::get('/student/dashboard', function(){
        return view('layouts.dashboard');
    })->name('dashboard');

    /**
     * SUBJECT
     */
    Route::resource('/student/subjects', 'student\SubjectsController', [
        'names' => [
            'index' => 'student.subjects.index',
        ]
    ]);
    /**
     * END OF SUBJECT
     */
    /**
     * CHAPTERS
     */
    Route::get('/student/subjects/{subject}/chapters','student\SubjectsController@show')->name('subjects.chapters.show');
     /**
      * END OF CHAPTERS
      */
    /**
     * QUIZ
     */
    Route::resource('/student/subject.test', 'student\TestsController');
    Route::get('/student/quiz', function (){

    })->name('quiz.index');
    Route::get('/student/quiz/single-question', function (){
        return view('student.quiz.single-question');
    })->name('quiz.question');

    Route::get('/student/subject/{subject}/test/{test}','student\TestsController@ready')->name('student.test.index');

    Route::get('/student/quiz/{test}/result','ResultsController@calculateResult')->name('quiz.result');

    Route::get('/subject/{subject}/test/{test}','student\TestsController@startTest')->name('tests.startTest')->middleware('isTestGiven');

    Route::post('ajax/ans','student\TestsController@processQuestion')->name('ajax.sendAnswer');
    Route::post('ajax/navigateQuestion','student\TestsController@navigateQuestion')->name('ajax.navigateQuestion');

    Route::post('ajax/navigate','student\TestsController@navigateFilledQuestion')->name('ajax.navigateFilledQuestion');

    Route::post('ajax/unmarked','student\TestsController@getUnmarkedQuestion')->name('ajax.unmarked');

    /**
      * END OF QUIZ
      */
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Student extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/student/SubjectsController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use App\Subject;
use App\Test;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $subjects = Subject::paginate(8);
        $arr = [];
        foreach($subjects as $subject){
            $subarr = [];
            $chapters = $subject->chapters()->where('subject_id',$subject->id)->get();
            $final_test = null;
            // dd(Carbon::now()->format('Y-m-d H:i:s'));
            $tests = $subject->tests()->where('test_type','schedule')->orderBy('scheduled_at','ASC')->whereDate('scheduled_at','>=',Carbon::now()->format('Y-m-d'))->get();
            // dd($tests);
            foreach($tests as $test){
                // dd($test);
                $testTime= Carbon::parse($test->scheduled_at);
                $startTime = $testTime->timestamp;
                $endTime = date("Y-m-d H:i:s",(($test->duration/1000)+$startTime));
                $isTestGiven = $test->users()->where('user_id',auth()->user()->id)->first();
                if($endTime >= Carbon::parse(now()->format('Y-m-d H:i:s')) && $isTestGiven==null)
                {
                    $final_test= $test;
                    break;
                }
            }
            $testTime = null;
            $startTime = null;
            $endTime = null;
            $now = null;
            if($final_test!=null){
                $testTime= Carbon::parse($final_test->scheduled_at);
                $startTime = $testTime->timestamp;
                $endTime = date("Y-m-d H:i:s",(($final_test->duration/1000)+$startTime));
                $now = Carbon::now();
            }
            $subarr[] = $subject;
            $subarr[] = $chapters;
            $subarr[] = $testTime;
            $subarr[] = $now;
            $subarr[] = $endTime;
            $subarr[] = $final_test;
            $arr[] = $subarr;
        }

        // dd($tests);
        return view('student.subjects.index',compact([
            'subjects','arr'
        ]));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        //
        $chapters = $subject->chapters()->where('subject_id',$subject->id)->get();
        $testChapter = $subject->tests()->where('subject_id',$subject->id)->get();
        // dd($testChapter);
        $final_test = null;
        // dd(Carbon::now()->format('Y-m-d H:i:s'));
        $tests = $subject->tests()->where('test_type','schedule')->orderBy('scheduled_at','ASC')->whereDate('scheduled_at','>=',Carbon::now()->format('Y-m-d'))->get();
        // dd($tests);
        foreach($tests as $test){
            // dd($test);
            $testTime= Carbon::parse($test->scheduled_at);
            $startTime = $testTime->timestamp;
            $endTime = date("Y-m-d H:i:s",(($test->duration/1000)+$startTime));
            $isTestGiven = $test->users()->where('user_id',auth()->user()->id)->first();
            if($endTime >= Carbon::parse(now()->format('Y-m-d H:i:s')) && $isTestGiven==null)
            {
                $final_test= $test;
                break;
            }
        }
        $testTime = null;
        $startTime = null;
        $endTime = null;
        $now = null;
        if($final_test!=null){
            $testTime= Carbon::parse($final_test->scheduled_at);
            $startTime = $testTime->timestamp;
            $endTime = date("Y-m-d H:i:s",(($final_test->duration/1000)+$startTime));
            $now = Carbon::now();
        }
        return view('student.chapters.show',compact([
            'subject','chapters','testTime','now','endTime','final_test','testChapter'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
    }
}

resources/views/student/quiz/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="wrapper d-flex flex-column mt-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow mb-4">
                    <div class="card-header">
                        <h6 class="m-0 font-weight-bold text-primary">
                            <i class="fa fa-plus mr-2"></i>Create Practice Test
                        </h6>
                    </div>
                    <!--CARD BODY-->
                    <div class="card-body">
                        <h2 class="text-muted" style="margin-bottom: 20px!important">Chapters</h2>
                        <form action="{{route('subject.test.store',$subject->id)}}" method="POST" id="add-test">
                            @csrf
                            @php
                                $i=1;
                            @endphp
                            @foreach ($subject->chapters as $chapter)
                                <div class="form-group">

                                    <div class="row">
                                        <div class="col-md-3">
                                            <label >{{$chapter->name}}</label>
                                        </div>

                                        <div class="col-md-1">
                                            <label class="kt-checkbox kt-checkbox--success justify-content-center">
                                                <input type="checkbox"
                                                        class="cb"
                                                        name="chapterSelected[]"
                                                        id="checkbox_{{$i}}" value="{{$chapter->id}}">

                                                <span></span>
                                            </label>
                                        </div>
                                        @php
                                            $maxMarks = $chapter->questions->sum('marks');
                                        @endphp

                                        <div class="col-md-2" id="keys">
                                            <input type="hidden" name="mainWeightage[]" id="w_{{$i}}">
                                            <input type="number"
                                                    name="weightage[]"
                                                    id="weightage_{{$i}}" value=""
                                                    placeholder="Weightage" class="d-inline form-control weightage {{ $errors->has('weightage') ? 'is-invalid' : '' }}"
                                                    disabled min="0" max="{{$maxMarks}}">
                                                    @error('weightage')
                                                         <div class="text-danger">{{ $message }}</div>
                                                    @enderror
                                        </div>
                                    </div>

                                </div>
                                @php
                                    $i++;
                                @endphp
                            @endforeach
                            <button type="submit" class="btn btn-outline-success">Create Test</button>
                        </form>
                    </div>
                    <!--/CARD BODY-->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

    <script>
        $(".cb").change(function(){

            var weightage = "#weightage_"+$(this).attr('id').split('_')[1];
            var w = "#w_"+$(this).attr('id').split('_')[1];
            var check = $(this);
            if ($(this).is(":checked"))
            {
                $(weightage).removeAttr('disabled');
            }
            else{
                $(weightage).val('');
                $(w).val('');
                $(weightage).attr('disabled',true);
            }
        });

        $('.weightage').keyup(function(){
            var weightage = $(this);
            var w = "#w_"+$(this).attr('id').split('_')[1];
            var check = "#checkbox_"+$(this).attr('id').split('_')[1];
            $(w).val($(check).val()+":"+$(weightage).val());

        });

    </script>
@endsection

resources/views/student/quiz/index.blade.php
@extends('layouts.dashboard')
@section('breadcrumb')
    <div class="breadcrumb-area">
        <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({{ asset('assets/student/img/bg/breadcrumb-bg-5.jpg') }});">
            <div class="container">
                <h2>Quiz</h2>
            </div>
        </div>
        <div class="breadcrumb-bottom">
            <div class="container">
                <ul>
                    <li>
                        <a href="#">Home</a>
                        <span class="ml-2">
                            <i class="fa fa-angle-double-right"></i>
                            Quiz
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <section class="quiz-view">
        <div class="container">
            <div class="quiz-title">
                <h2>{{$test->subjects[0]->name}} {{$test->test_type}} Test</h2>

            </div>
            <div class="row">

                <div class="col-sm-8 col-md-9">
                    <div class="quiz-intro">
                        <h3>Instruction</h3>
                        <div class="form-group form-group-last">
                            <div class="alert pl-0" role="alert">
                                <div class="alert-icon pl-1"><i class="flaticon-warning kt-font-brand"></i></div>
                                <div class="alert-text">
                                    Refreshing the page, Changing tabs will <code>END THE TEST</code>
                                </div>
                            </div>
                        </div>
                        <div class="start-btn">
                            <a href="{{ route('tests.startTest',[$subject,$test]) }}" class="btn btn-lg btn-primary">Start Quizz</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/student/quiz/result.blade.php
@extends('layouts.dashboard')

@section('content')
    <section class="quiz-view">
        <div class="container">
            @if ($final_ans->isEmpty())
                <p class="text-success">Your test has been successfully submitted. All the Best for your results</p>
            @endif
            @if(!$final_ans->isEmpty())
                <div class="result d-flex justify-content-between">
                    <h3 class="title">Result:</h3>
                    <h3>You scored:<strong> {{$marks.'/'.$totMarks}}</strong></h3>
                </div>
                @foreach ($final_ans as $item)
                    <div class="col-md-12 pt-2">
                        <div class="qustion-main">
                            <div class="qustion-box">
                                <div  id="question-box">
                                    <div class="d-flex justify-content-between qustion">
                                        <div id="question-data" data-id="1" class="">{{$item[0]->question}}</div>
                                        <div id="marks" class="{{$item[1]->id == $item[2]->id ? 'correct':'wrong'}}">{{$item[0]->marks}} Marks</div>
                                    </div>
                                    <input type="hidden" value="" id="question">
                                    <div class="ans">
                                        @if ($item[1]->id == $item[2]->id)
                                            <div class="ans-slide">
                                                <p class="myAnswer m-0">Your answer:</p>
                                                <span class="correct">{{$item[1]->answer}}</span>
                                            </div>
                                        @else
                                            <div class="ans-slide">
                                                <p class="myAnswer m-0">Your answer:</p>
                                                <span class="wrong">{{$item[1]->answer}}</span>
                                            </div>
                                            <div class="ans-slide">
                                                <p class="myAnswer m-0">Correct answer:</p>
                                                <span class="correct">{{$item[2]->answer}}</span>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            @endif
            </div>
    </section>
@endsection
@section('scripts')
<script type="text/javascript">
    function preventBack() {
        window.history.forward();
    }

    setTimeout("preventBack()", 0);

    window.onunload = function () { null };
</script>
@endsection