routes/web.php
<?php

use App\Http\Controllers\ResultsController;
use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/**
 * ADMIN ROUTES
 */
Route::middleware(['verifyAdmin'])->group(function(){

    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('dashboard');
    Route::get('/cpanel/users', 'admin\UsersController@index')->name('users.index');


// Route::get('/cpanel/subject.chapter','admin\ChaptersController')->except(['index','show']);

    //new changes
    Route::get('/cpanel/chapters/create', 'admin\ChaptersController@createChapter')->name('createChapter');
    Route::get('/cpanel/chapters', 'admin\ChaptersController@indexChapter')->name('indexChapter');
    //end of new changes

    Route::resource('/cpanel/subject.chapters','admin\ChaptersController')->except(['edit','update','destroy']);
    Route::get('/cpanel/chapter/{chapter}/edit','admin\ChaptersController@editChapter')->name('chapter.editChapter');
    Route::put('/cpanel/chapter/{chapter}/update','admin\ChaptersController@updateChapter')->name('chapter.updateChapter');
    Route::delete('/cpanel/chapter/{chapter}/delete','admin\ChaptersController@destroyChapter')->name('chapter.destroyChapter');

    /**
     * QUESTIONS
     */
    Route::resource('/cpanel/chapter.questions', 'admin\QuestionsController');
    Route::get('/cpanel/chapters/{chapter}/questions/create','admin\QuestionsController@createQuestion')->name('questions.createQuestion');
    Route::get('/cpanel/chapters/{chapter}/questions/{question}/edit','admin\QuestionsController@editQuestion')->name('questions.editQuestion');
    /**
     * END OF QUESTIONS
     */

    /**
     * SUBJECTS
     */
    Route::resource('/cpanel/subjects','admin\SubjectsController');

    Route::resource('/cpanel/subjects.tests','admin\TestsController')->except(['edit','update','destroy']);
    /**
     * END OF SUBJECTS
     */

    Route::get('/cpanel/quiz/{test}/result','admin\ResultsController@getResult')->name('test.result');

});

/**
 * STUDENT ROUTES
 */
Route::middleware(['auth','verifyStudent'])->group(function(){

    Route::get('/student/dashboard', function(){
        return view('layouts.dashboard');
    })->name('dashboard');

    /**
     * SUBJECT
     */
    Route::resource('/student/subjects', 'student\SubjectsController', [
        'names' => [
            'index' => 'student.subjects.index',
        ]
    ]);
    /**
     * END OF SUBJECT
     */
    /**
     * CHAPTERS
     */
    Route::get('/student/subjects/{subject}/chapters','student\SubjectsController@show')->name('subjects.chapters.show');
     /**
      * END OF CHAPTERS
      */
    /**
     * QUIZ
     */
    Route::resource('/student/subject.test', 'student\TestsController');
    Route::get('/student/quiz', function (){

    })->name('quiz.index');
    Route::get('/student/quiz/single-question', function (){
        return view('student.quiz.single-question');
    })->name('quiz.question');

    Route::get('/student/subject/{subject}/test/{test}','student\TestsController@ready')->name('student.test.index');

    Route::get('/student/quiz/{test}/result','ResultsController@calculateResult')->name('quiz.result');

    Route::get('/subject/{subject}/test/{test}','student\TestsController@startTest')->name('tests.startTest')->middleware('isTestGiven');

    Route::post('ajax/ans','student\TestsController@processQuestion')->name('ajax.sendAnswer');
    Route::post('ajax/navigateQuestion','student\TestsController@navigateQuestion')->name('ajax.navigateQuestion');

    Route::post('ajax/navigate','student\TestsController@navigateFilledQuestion')->name('ajax.navigateFilledQuestion');

    Route::post('ajax/unmarked','student\TestsController@getUnmarkedQuestion')->name('ajax.unmarked');

    /**
      * END OF QUIZ
      */
});

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Chapter;
use Illuminate\Database\Eloquent\SoftDeletes;
class Subject extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    public function chapters(){
        return $this->hasMany(Chapter::class);
    }
    public function tests(){
        return $this->belongsToMany(Test::class);
    }
}

app/Http/Controllers/admin/SubjectsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Chapter;
use App\Subject;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\SoftDeletes;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjects = Subject::withoutTrashed()->get();
        return view('admin.subjects.index',compact([
            'subjects'
        ]));

        ///

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function show(Chapter $chapter)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function edit(Chapter $chapter)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Chapter $chapter)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Chapter $chapter)
    {
        //
    }
}

app/Http/Controllers/student/SubjectsController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use App\Subject;
use App\Test;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $subjects = Subject::paginate(8);
        $arr = [];
        foreach($subjects as $subject){
            $subarr = [];
            $chapters = $subject->chapters()->where('subject_id',$subject->id)->get();
            $final_test = null;
            // dd(Carbon::now()->format('Y-m-d H:i:s'));
            $tests = $subject->tests()->where('test_type','schedule')->orderBy('scheduled_at','ASC')->whereDate('scheduled_at','>=',Carbon::now()->format('Y-m-d'))->get();
            // dd($tests);
            foreach($tests as $test){
                // dd($test);
                $testTime= Carbon::parse($test->scheduled_at);
                $startTime = $testTime->timestamp;
                $endTime = date("Y-m-d H:i:s",(($test->duration/1000)+$startTime));
                $isTestGiven = $test->users()->where('user_id',auth()->user()->id)->first();
                if($endTime >= Carbon::parse(now()->format('Y-m-d H:i:s')) && $isTestGiven==null)
                {
                    $final_test= $test;
                    break;
                }
            }
            $testTime = null;
            $startTime = null;
            $endTime = null;
            $now = null;
            if($final_test!=null){
                $testTime= Carbon::parse($final_test->scheduled_at);
                $startTime = $testTime->timestamp;
                $endTime = date("Y-m-d H:i:s",(($final_test->duration/1000)+$startTime));
                $now = Carbon::now();
            }
            $subarr[] = $subject;
            $subarr[] = $chapters;
            $subarr[] = $testTime;
            $subarr[] = $now;
            $subarr[] = $endTime;
            $subarr[] = $final_test;
            $arr[] = $subarr;
        }

        // dd($tests);
        return view('student.subjects.index',compact([
            'subjects','arr'
        ]));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        //
        $chapters = $subject->chapters()->where('subject_id',$subject->id)->get();
        $testChapter = $subject->tests()->where('subject_id',$subject->id)->get();
        // dd($testChapter);
        $final_test = null;
        // dd(Carbon::now()->format('Y-m-d H:i:s'));
        $tests = $subject->tests()->where('test_type','schedule')->orderBy('scheduled_at','ASC')->whereDate('scheduled_at','>=',Carbon::now()->format('Y-m-d'))->get();
        // dd($tests);
        foreach($tests as $test){
            // dd($test);
            $testTime= Carbon::parse($test->scheduled_at);
            $startTime = $testTime->timestamp;
            $endTime = date("Y-m-d H:i:s",(($test->duration/1000)+$startTime));
            $isTestGiven = $test->users()->where('user_id',auth()->user()->id)->first();
            if($endTime >= Carbon::parse(now()->format('Y-m-d H:i:s')) && $isTestGiven==null)
            {
                $final_test= $test;
                break;
            }
        }
        $testTime = null;
        $startTime = null;
        $endTime = null;
        $now = null;
        if($final_test!=null){
            $testTime= Carbon::parse($final_test->scheduled_at);
            $startTime = $testTime->timestamp;
            $endTime = date("Y-m-d H:i:s",(($final_test->duration/1000)+$startTime));
            $now = Carbon::now();
        }
        return view('student.chapters.show',compact([
            'subject','chapters','testTime','now','endTime','final_test','testChapter'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
    }
}

resources/views/admin/subjects/index.blade.php
@extends('layouts.dashboard')
@section('title','Subjects')
@section('content')
    <div class="wrapper d-flex flex-column mt-4">
        <div class="container-fluid">
            <div id="kt_wrapper">
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
                <!-- begin:: Content -->
                    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

                        <div class="kt-portlet kt-portlet--mobile">
                            <div class="kt-portlet__head kt-portlet__head--lg">
                                <div class="kt-portlet__head-label">
                                    <span class="kt-portlet__head-icon">
                                        <i class="kt-font-brand flaticon2-line-chart"></i>
                                    </span>
                                    <h3 class="kt-portlet__head-title">
                                        Basic
                                    </h3>
                                </div>
                                <div class="kt-portlet__head-toolbar">
                                    <div class="kt-portlet__head-wrapper">
                                        <div class="kt-portlet__head-actions">
                                            <div class="dropdown dropdown-inline">
                                                <button type="button" class="btn btn-default btn-icon-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="la la-download"></i> Export
                                                </button>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul class="kt-nav">
                                                        <li class="kt-nav__section kt-nav__section--first">
                                                            <span class="kt-nav__section-text">Choose an option</span>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-print"></i>
                                                                <span class="kt-nav__link-text">Print</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-copy"></i>
                                                                <span class="kt-nav__link-text">Copy</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-file-excel-o"></i>
                                                                <span class="kt-nav__link-text">Excel</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-file-text-o"></i>
                                                                <span class="kt-nav__link-text">CSV</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-file-pdf-o"></i>
                                                                <span class="kt-nav__link-text">PDF</span>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            &nbsp;
                                            <a href="#" class="btn btn-brand btn-elevate btn-icon-sm">
                                                <i class="la la-plus"></i>
                                                New Subject
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="kt-portlet__body">

                                <!--begin: Datatable -->
                                <table class="table table-striped- table-bordered table-hover table-checkable" id="subject_table">
                                    <thead>
                                        <tr>
                                            <th>Subject ID</th>
                                            <th>Name</th>
                                            <th>Chapter Count</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($subjects as $subject)
                                            <tr>
                                                <td>{{$subject->id}}</td>
                                                <td>{{$subject->name}}</td>
                                                <td>{{$subject->chapters()->withoutTrashed()->count()}}</td>
                                                <td> <a href="{{route('subject.chapters.index',$subject->id)}}" class='btn btn-outline-success btn-sm m-1'><i class='kt-menu__link-icon flaticon-eye'></i>View</a>
                                                     <a href="" class='btn btn-outline-primary btn-sm m-1 '><i class='kt-menu__link-icon flaticon-edit'></i>Edit</a>
                                                     <a href="" class='btn btn-outline-danger btn-sm m-1 '><i class='kt-menu__link-icon flaticon2-trash'></i>Delete</a>
                                                     <a href="{{route('subjects.tests.index',$subject->id)}}" class='btn btn-outline-info btn-sm m-1 '><i class='kt-menu__link-icon flaticon-book'></i>Tests</a>

                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>

                                <!--end: Datatable -->
                            </div>
                        </div>
                    </div>

                    <!-- end:: Content -->
                </div>
            </div>
        </div>

        <!-- end:: Content -->
    </div>
@endsection
@section('styles')
    <!--begin::Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">
    <!--end::Fonts -->

    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="{{ asset('assets/admin/plugins/custom/fullcalendar/fullcalendar.bundle.css')}}" rel="stylesheet" type="text/css" />
    <!--end::Page Vendors Styles -->

    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="{{ asset('assets/admin/plugins/global/plugins.bundle.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/admin/css/style.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('scripts')
    <script src="{{asset('assets/admin/plugins/global/plugins.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/admin/js/scripts.bundle.js')}}" type="text/javascript"></script>
    <!-- end::Global Config -->

    <!--begin::Page Vendors(used by this page) -->
    <script src="{{ asset('assets/admin/plugins/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>

    <!--end::Page Vendors -->

    <!--begin::Page Scripts(used by this page) -->
    <script src="{{ asset('assets/admin/js/pages/crud/datatables/basic/paginations.js')}}" type="text/javascript"></script>
    <script>
        $(document).ready( function() {
	        $('#subject_table').DataTable();
	    });
    </script>
@endsection