routes/web.php
<?php

use App\Http\Controllers\ResultsController;
use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/**
 * ADMIN ROUTES
 */
Route::middleware(['verifyAdmin'])->group(function(){

    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('dashboard');
    Route::get('/cpanel/users', 'admin\UsersController@index')->name('users.index');


// Route::get('/cpanel/subject.chapter','admin\ChaptersController')->except(['index','show']);

    //new changes
    Route::get('/cpanel/chapters/create', 'admin\ChaptersController@createChapter')->name('createChapter');
    Route::get('/cpanel/chapters', 'admin\ChaptersController@indexChapter')->name('indexChapter');
    //end of new changes

    Route::resource('/cpanel/subject.chapters','admin\ChaptersController')->except(['edit','update','destroy']);
    Route::get('/cpanel/chapter/{chapter}/edit','admin\ChaptersController@editChapter')->name('chapter.editChapter');
    Route::put('/cpanel/chapter/{chapter}/update','admin\ChaptersController@updateChapter')->name('chapter.updateChapter');
    Route::delete('/cpanel/chapter/{chapter}/delete','admin\ChaptersController@destroyChapter')->name('chapter.destroyChapter');

    /**
     * QUESTIONS
     */
    Route::resource('/cpanel/chapter.questions', 'admin\QuestionsController');
    Route::get('/cpanel/chapters/{chapter}/questions/create','admin\QuestionsController@createQuestion')->name('questions.createQuestion');
    Route::get('/cpanel/chapters/{chapter}/questions/{question}/edit','admin\QuestionsController@editQuestion')->name('questions.editQuestion');
    /**
     * END OF QUESTIONS
     */

    /**
     * SUBJECTS
     */
    Route::resource('/cpanel/subjects','admin\SubjectsController');

    Route::resource('/cpanel/subjects.tests','admin\TestsController')->except(['edit','update','destroy']);
    /**
     * END OF SUBJECTS
     */

    Route::get('/cpanel/quiz/{test}/result','admin\ResultsController@getResult')->name('test.result');

});

/**
 * STUDENT ROUTES
 */
Route::middleware(['auth','verifyStudent'])->group(function(){

    Route::get('/student/dashboard', function(){
        return view('layouts.dashboard');
    })->name('dashboard');

    /**
     * SUBJECT
     */
    Route::resource('/student/subjects', 'student\SubjectsController', [
        'names' => [
            'index' => 'student.subjects.index',
        ]
    ]);
    /**
     * END OF SUBJECT
     */
    /**
     * CHAPTERS
     */
    Route::get('/student/subjects/{subject}/chapters','student\SubjectsController@show')->name('subjects.chapters.show');
     /**
      * END OF CHAPTERS
      */
    /**
     * QUIZ
     */
    Route::resource('/student/subject.test', 'student\TestsController');
    Route::get('/student/quiz', function (){

    })->name('quiz.index');
    Route::get('/student/quiz/single-question', function (){
        return view('student.quiz.single-question');
    })->name('quiz.question');

    Route::get('/student/subject/{subject}/test/{test}','student\TestsController@ready')->name('student.test.index');

    Route::get('/student/quiz/{test}/result','ResultsController@calculateResult')->name('quiz.result');

    Route::get('/subject/{subject}/test/{test}','student\TestsController@startTest')->name('tests.startTest')->middleware('isTestGiven');

    Route::post('ajax/ans','student\TestsController@processQuestion')->name('ajax.sendAnswer');
    Route::post('ajax/navigateQuestion','student\TestsController@navigateQuestion')->name('ajax.navigateQuestion');

    Route::post('ajax/navigate','student\TestsController@navigateFilledQuestion')->name('ajax.navigateFilledQuestion');

    Route::post('ajax/unmarked','student\TestsController@getUnmarkedQuestion')->name('ajax.unmarked');

    /**
      * END OF QUIZ
      */
});

app/Chapter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Chapter extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    public function subject(){
        return $this->belongsTo(Subject::class);
    }
    public function questions(){
        return $this->hasMany(Question::class);
    }
    public function tests(){
        return $this->belongsToMany(Test::class)->withPivot('weightage');
    }
}

app/Http/Controllers/admin/ChaptersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Chapter;
use App\Subject;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ChaptersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Subject $subject)
    {
        //yeh sab subjects laaega
        // $chapters = Chapter::withoutTrashed()->get();
        // return view('admin.chapters.index',compact(
        //     'chapters'
        // ));
        //yeh subject ka chapters laaega
        $chapters = $subject->chapters()->withoutTrashed()->get();
        return view('admin.chapters.index',compact([
            'subject','chapters'
        ]));
    }
    public function create(Subject $subject)
    {
        return view('admin.chapters.create',compact([
            'subject'
        ]));
    }
    public function show()
    {
       //
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Subject $subject)
    {
        $data = $request->all();
        foreach($data['name'] as $chapter){
            $subject->chapters()->create([
                'name' => $chapter
            ]);
        }
        return redirect(route('subject.chapters.index',$subject));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function editChapter(Chapter $chapter)
    {
        return view('admin.chapters.edit',compact([
            'chapter'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function updateChapter(Request $request, Chapter $chapter)
    {
        $data = $request->all();
        $chapter->update([
            'name'=> $data['name']
        ]);
        $subject = $chapter->subject;
        $chapters = $subject->chapters()->withoutTrashed()->get();
        return view('admin.chapters.index',compact([
            'subject','chapters'
        ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function destroyChapter(Chapter $chapter)
    {
        if(count($chapter->questions)==0){
            $chapter->delete();
        }
        return redirect()->back();
    }

    public function createChapter()
    {
        //yeh function hai jab chapters se create kia aur subject id nai hai toh sab subjects bhejra hu dropdown ke liye
       $subjects = Subject::all();
       $subject = null;
        // dd($subject==-1);
        return view('admin.chapters.create',compact([
            'subject','subjects'
        ]));
    }
    public function indexChapter()
    {
        $subject = null;
        // yeh sab subjects laaega
        $chapters = Chapter::withoutTrashed()->get();
        return view('admin.chapters.index',compact(
            'chapters','subject'
        ));
    }
}

resources/views/admin/chapters/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="wrapper d-flex flex-column mt-4">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card shadow mb-4">
                <div class="card-header">
                  <h6 class="m-0 font-weight-bold text-primary">
                    <i class="fa fa-plus"></i>Add Chapters
                  </h6>
                </div>
                <!--CARD BODY-->
                <div class="card-body">
                    <form action="{{$subject!=null?route('subject.chapters.store',[$subject->id]):''}}" method="POST" id="add-category">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                @if ($subject==null)

                                    <div class="form-group" id="subject">
                                        <div>
                                            <label>Subject</label>
                                            <select name="subject_id" id="subject_id"  class="custom-select form-control">
                                                    <option value="" selected disabled>Select</option>
                                                @foreach ($subjects as $subject)
                                                    <option value="{{$subject->id}}">{{$subject->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                @endif

                                <div class="form-group" id="chapters">
                                    <div class="d-flex justify-content-between mb-2">
                                        <label>Chapter Name</label>
                                        <div class="btn btn-outline-primary mb-3" id="add-chapter" onclick="myFunction()">Add More Chapter</div>
                                    </div>
                                    <input type="text" class="form-control" name="name[]" id="name" placeholder="Enter Chapter name" value = "">
                                </div>
                            </div>
                        </div>
                        <input type="submit" name="add_category" class="btn btn-outline-success" value="Submit">
                    </form>
                </div>
                <!--/CARD BODY-->
              </div>
            </div>
          </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/ui/1.8.0/jquery-ui.js" integrity="sha256-d/98Bs8aAQdn5s3reV2fU8guAodmF4UhPjEt/pVkiJo=" crossorigin="anonymous"></script>
    <script>
        function myFunction(){
            var chapter = document.getElementById('chapters');
            $('#chapters').append(`<input type="text" class="form-control mt-3" name="name[]" id="name" placeholder="Enter Chapter name" value = "">`);
        }


        $('#subject_id').change(function() {
            val = $(this).val();
            var url = '{{ route("subject.chapters.store", ":id") }}';
            url = url.replace(':id', val);
            $("#add-category").attr('action',url);
        });
    </script>
@endsection

resources/views/admin/chapters/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="wrapper d-flex flex-column mt-4">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card shadow mb-4">
                <div class="card-header">
                  <h6 class="m-0 font-weight-bold text-primary">
                    <i class="fa fa-plus"></i>Add Chapters
                  </h6>
                </div>
                <!--CARD BODY-->
                <div class="card-body">
                  <form action="{{ route('chapter.updateChapter',$chapter->id) }}" method="POST" id="add-category">
                    @csrf
                    @method('PUT')
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group" id="chapters">
                            <div class="d-flex justify-content-between mb-2">
                                <label>Chapter Name</label>
                            </div>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Enter Category name" value = "{{$chapter->name}}">
                        </div>
                      </div>
                    </div>
                    <input type="submit" name="add_category" class="btn btn-primary" value="Submit">
                  </form>
                </div>
                <!--/CARD BODY-->
              </div>
            </div>
          </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://code.jquery.com/ui/1.8.0/jquery-ui.js" integrity="sha256-d/98Bs8aAQdn5s3reV2fU8guAodmF4UhPjEt/pVkiJo=" crossorigin="anonymous"></script>
@endsection

resources/views/admin/chapters/index.blade.php
@extends('layouts.dashboard')
@section('styles')
    <style>
        form{
            display:inline-block;
        }
    </style>
@endsection
@section('content')
    <div class="wrapper d-flex flex-column mt-4">
        <div class="container-fluid">
            <div id="kt_wrapper">
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
                    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
                        <div class="kt-portlet kt-portlet--mobile">
                            <div class="kt-portlet__head kt-portlet__head--lg">
                                <div class="kt-portlet__head-label">
                                    <span class="kt-portlet__head-icon">
                                        <i class="kt-font-brand flaticon2-line-chart"></i>
                                    </span>
                                    <h3 class="kt-portlet__head-title">
                                        Extended Pagination
                                    </h3>
                                </div>
                                <div class="kt-portlet__head-toolbar">
                                    <div class="kt-portlet__head-wrapper">
                                        <div class="kt-portlet__head-actions">
                                            <div class="dropdown dropdown-inline">
                                                <button type="button" class="btn btn-default btn-icon-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="la la-download"></i> Export
                                                </button>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul class="kt-nav">
                                                        <li class="kt-nav__section kt-nav__section--first">
                                                            <span class="kt-nav__section-text">Choose an option</span>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-print"></i>
                                                                <span class="kt-nav__link-text">Print</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-copy"></i>
                                                                <span class="kt-nav__link-text">Copy</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-file-excel-o"></i>
                                                                <span class="kt-nav__link-text">Excel</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-file-text-o"></i>
                                                                <span class="kt-nav__link-text">CSV</span>
                                                            </a>
                                                        </li>
                                                        <li class="kt-nav__item">
                                                            <a href="#" class="kt-nav__link">
                                                                <i class="kt-nav__link-icon la la-file-pdf-o"></i>
                                                                <span class="kt-nav__link-text">PDF</span>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            &nbsp;
                                            @if($subject==null)
                                                <a href="{{ route('createChapter') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                                                    <i class="la la-plus"></i>
                                                    New Chapter
                                                </a>
                                            @else
                                                <a href="{{ route('subject.chapters.create',[$subject->id]) }}" class="btn btn-brand btn-elevate btn-icon-sm">
                                                    <i class="la la-plus"></i>
                                                    New Chapter
                                                </a>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="kt-portlet__body">
                                <!--begin: Datatable -->
                                <table class="table table-striped- table-bordered table-hover table-checkable" id="chapter_table">
                                    <thead>
                                        <tr>
                                            <th>Chapter Name</th>
                                            <th>Questions</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($chapters as $chapter)
                                            <tr>
                                                <td>{{$chapter->name}}</td>
                                                <td>{{$chapter->questions()->withoutTrashed()->count()}}</td>
                                                <td>
                                                    <a href="{{ route('chapter.questions.index',$chapter->id) }}"> <button class='btn btn-outline-success btn-sm m-1'><i class='kt-menu__link-icon flaticon-eye'></i>View</button></a>
                                                    <a href="{{ route('chapter.editChapter',[$chapter->id]) }}"><button class='btn btn-outline-primary btn-sm m-1 '><i class='kt-menu__link-icon flaticon-edit'></i>Edit</button></a>
                                                    <form action="{{ route('chapter.destroyChapter',$chapter->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('Are you sure you want to delete?');" class='btn btn-outline-danger btn-sm m-1 '><i class='kt-menu__link-icon flaticon2-trash'></i>Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                <!--end: Datatable -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

@section('styles')
    <!--begin::Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">
    <!--end::Fonts -->

    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="{{ asset('assets/admin/plugins/custom/fullcalendar/fullcalendar.bundle.css')}}" rel="stylesheet" type="text/css" />
    <!--end::Page Vendors Styles -->

    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="{{ asset('assets/admin/plugins/global/plugins.bundle.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/admin/css/style.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('scripts')
    <script src="{{asset('assets/admin/plugins/global/plugins.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/admin/js/scripts.bundle.js')}}" type="text/javascript"></script>
    <!-- end::Global Config -->

    <!--begin::Page Vendors(used by this page) -->
    <script src="{{ asset('assets/admin/plugins/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>

    <!--end::Page Vendors -->

    <!--begin::Page Scripts(used by this page) -->
    <script src="{{ asset('assets/admin/js/pages/crud/datatables/basic/paginations.js')}}" type="text/javascript"></script>
    <script>
        $(document).ready( function() {
	        $('#chapter_table').DataTable();
	    });
    </script>
@endsection