routes/web.php
<?php

use App\Http\Controllers\ResultsController;
use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/**
 * ADMIN ROUTES
 */
Route::middleware(['verifyAdmin'])->group(function(){

    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('dashboard');
    Route::get('/cpanel/users', 'admin\UsersController@index')->name('users.index');


// Route::get('/cpanel/subject.chapter','admin\ChaptersController')->except(['index','show']);

    //new changes
    Route::get('/cpanel/chapters/create', 'admin\ChaptersController@createChapter')->name('createChapter');
    Route::get('/cpanel/chapters', 'admin\ChaptersController@indexChapter')->name('indexChapter');
    //end of new changes

    Route::resource('/cpanel/subject.chapters','admin\ChaptersController')->except(['edit','update','destroy']);
    Route::get('/cpanel/chapter/{chapter}/edit','admin\ChaptersController@editChapter')->name('chapter.editChapter');
    Route::put('/cpanel/chapter/{chapter}/update','admin\ChaptersController@updateChapter')->name('chapter.updateChapter');
    Route::delete('/cpanel/chapter/{chapter}/delete','admin\ChaptersController@destroyChapter')->name('chapter.destroyChapter');

    /**
     * QUESTIONS
     */
    Route::resource('/cpanel/chapter.questions', 'admin\QuestionsController');
    Route::get('/cpanel/chapters/{chapter}/questions/create','admin\QuestionsController@createQuestion')->name('questions.createQuestion');
    Route::get('/cpanel/chapters/{chapter}/questions/{question}/edit','admin\QuestionsController@editQuestion')->name('questions.editQuestion');
    /**
     * END OF QUESTIONS
     */

    /**
     * SUBJECTS
     */
    Route::resource('/cpanel/subjects','admin\SubjectsController');

    Route::resource('/cpanel/subjects.tests','admin\TestsController')->except(['edit','update','destroy']);
    /**
     * END OF SUBJECTS
     */

    Route::get('/cpanel/quiz/{test}/result','admin\ResultsController@getResult')->name('test.result');

});

/**
 * STUDENT ROUTES
 */
Route::middleware(['auth','verifyStudent'])->group(function(){

    Route::get('/student/dashboard', function(){
        return view('layouts.dashboard');
    })->name('dashboard');

    /**
     * SUBJECT
     */
    Route::resource('/student/subjects', 'student\SubjectsController', [
        'names' => [
            'index' => 'student.subjects.index',
        ]
    ]);
    /**
     * END OF SUBJECT
     */
    /**
     * CHAPTERS
     */
    Route::get('/student/subjects/{subject}/chapters','student\SubjectsController@show')->name('subjects.chapters.show');
     /**
      * END OF CHAPTERS
      */
    /**
     * QUIZ
     */
    Route::resource('/student/subject.test', 'student\TestsController');
    Route::get('/student/quiz', function (){

    })->name('quiz.index');
    Route::get('/student/quiz/single-question', function (){
        return view('student.quiz.single-question');
    })->name('quiz.question');

    Route::get('/student/subject/{subject}/test/{test}','student\TestsController@ready')->name('student.test.index');

    Route::get('/student/quiz/{test}/result','ResultsController@calculateResult')->name('quiz.result');

    Route::get('/subject/{subject}/test/{test}','student\TestsController@startTest')->name('tests.startTest')->middleware('isTestGiven');

    Route::post('ajax/ans','student\TestsController@processQuestion')->name('ajax.sendAnswer');
    Route::post('ajax/navigateQuestion','student\TestsController@navigateQuestion')->name('ajax.navigateQuestion');

    Route::post('ajax/navigate','student\TestsController@navigateFilledQuestion')->name('ajax.navigateFilledQuestion');

    Route::post('ajax/unmarked','student\TestsController@getUnmarkedQuestion')->name('ajax.unmarked');

    /**
      * END OF QUIZ
      */
});

app/Chapter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Chapter extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    public function subject(){
        return $this->belongsTo(Subject::class);
    }
    public function questions(){
        return $this->hasMany(Question::class);
    }
    public function tests(){
        return $this->belongsToMany(Test::class)->withPivot('weightage');
    }
}

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Student extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/admin/ChaptersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Chapter;
use App\Subject;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ChaptersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Subject $subject)
    {
        //yeh sab subjects laaega
        // $chapters = Chapter::withoutTrashed()->get();
        // return view('admin.chapters.index',compact(
        //     'chapters'
        // ));
        //yeh subject ka chapters laaega
        $chapters = $subject->chapters()->withoutTrashed()->get();
        return view('admin.chapters.index',compact([
            'subject','chapters'
        ]));
    }
    public function create(Subject $subject)
    {
        return view('admin.chapters.create',compact([
            'subject'
        ]));
    }
    public function show()
    {
       //
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Subject $subject)
    {
        $data = $request->all();
        foreach($data['name'] as $chapter){
            $subject->chapters()->create([
                'name' => $chapter
            ]);
        }
        return redirect(route('subject.chapters.index',$subject));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function editChapter(Chapter $chapter)
    {
        return view('admin.chapters.edit',compact([
            'chapter'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function updateChapter(Request $request, Chapter $chapter)
    {
        $data = $request->all();
        $chapter->update([
            'name'=> $data['name']
        ]);
        $subject = $chapter->subject;
        $chapters = $subject->chapters()->withoutTrashed()->get();
        return view('admin.chapters.index',compact([
            'subject','chapters'
        ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Chapter  $chapter
     * @return \Illuminate\Http\Response
     */
    public function destroyChapter(Chapter $chapter)
    {
        if(count($chapter->questions)==0){
            $chapter->delete();
        }
        return redirect()->back();
    }

    public function createChapter()
    {
        //yeh function hai jab chapters se create kia aur subject id nai hai toh sab subjects bhejra hu dropdown ke liye
       $subjects = Subject::all();
       $subject = null;
        // dd($subject==-1);
        return view('admin.chapters.create',compact([
            'subject','subjects'
        ]));
    }
    public function indexChapter()
    {
        $subject = null;
        // yeh sab subjects laaega
        $chapters = Chapter::withoutTrashed()->get();
        return view('admin.chapters.index',compact(
            'chapters','subject'
        ));
    }
}

app/Http/Controllers/student/SubjectsController.php
<?php

namespace App\Http\Controllers\student;

use App\Http\Controllers\Controller;
use App\Subject;
use App\Test;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SubjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $subjects = Subject::paginate(8);
        $arr = [];
        foreach($subjects as $subject){
            $subarr = [];
            $chapters = $subject->chapters()->where('subject_id',$subject->id)->get();
            $final_test = null;
            // dd(Carbon::now()->format('Y-m-d H:i:s'));
            $tests = $subject->tests()->where('test_type','schedule')->orderBy('scheduled_at','ASC')->whereDate('scheduled_at','>=',Carbon::now()->format('Y-m-d'))->get();
            // dd($tests);
            foreach($tests as $test){
                // dd($test);
                $testTime= Carbon::parse($test->scheduled_at);
                $startTime = $testTime->timestamp;
                $endTime = date("Y-m-d H:i:s",(($test->duration/1000)+$startTime));
                $isTestGiven = $test->users()->where('user_id',auth()->user()->id)->first();
                if($endTime >= Carbon::parse(now()->format('Y-m-d H:i:s')) && $isTestGiven==null)
                {
                    $final_test= $test;
                    break;
                }
            }
            $testTime = null;
            $startTime = null;
            $endTime = null;
            $now = null;
            if($final_test!=null){
                $testTime= Carbon::parse($final_test->scheduled_at);
                $startTime = $testTime->timestamp;
                $endTime = date("Y-m-d H:i:s",(($final_test->duration/1000)+$startTime));
                $now = Carbon::now();
            }
            $subarr[] = $subject;
            $subarr[] = $chapters;
            $subarr[] = $testTime;
            $subarr[] = $now;
            $subarr[] = $endTime;
            $subarr[] = $final_test;
            $arr[] = $subarr;
        }

        // dd($tests);
        return view('student.subjects.index',compact([
            'subjects','arr'
        ]));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        //
        $chapters = $subject->chapters()->where('subject_id',$subject->id)->get();
        $testChapter = $subject->tests()->where('subject_id',$subject->id)->get();
        // dd($testChapter);
        $final_test = null;
        // dd(Carbon::now()->format('Y-m-d H:i:s'));
        $tests = $subject->tests()->where('test_type','schedule')->orderBy('scheduled_at','ASC')->whereDate('scheduled_at','>=',Carbon::now()->format('Y-m-d'))->get();
        // dd($tests);
        foreach($tests as $test){
            // dd($test);
            $testTime= Carbon::parse($test->scheduled_at);
            $startTime = $testTime->timestamp;
            $endTime = date("Y-m-d H:i:s",(($test->duration/1000)+$startTime));
            $isTestGiven = $test->users()->where('user_id',auth()->user()->id)->first();
            if($endTime >= Carbon::parse(now()->format('Y-m-d H:i:s')) && $isTestGiven==null)
            {
                $final_test= $test;
                break;
            }
        }
        $testTime = null;
        $startTime = null;
        $endTime = null;
        $now = null;
        if($final_test!=null){
            $testTime= Carbon::parse($final_test->scheduled_at);
            $startTime = $testTime->timestamp;
            $endTime = date("Y-m-d H:i:s",(($final_test->duration/1000)+$startTime));
            $now = Carbon::now();
        }
        return view('student.chapters.show',compact([
            'subject','chapters','testTime','now','endTime','final_test','testChapter'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        //
    }
}

resources/views/student/chapters/show.blade.php
@extends('layouts.dashboard')

@section('content')
    <section id="scheduled-test">
        <div>
            <div class="card text-center">
                <div class="card-body">
                    <h3>
                        Scheduled Test:
                        @if ($testTime == null || $now>$endTime || $final_test==null)
                            No upcoming tests
                        @elseif($now>=$testTime && $now<$endTime)
                            <a href="{{route('student.test.index',[$subject->id,$final_test->id])}}">{{$subject->name}} Test</a>
                        @elseif($now<$testTime)
                            <strong> {{$testTime->diffForHumans().' : '.$testTime}}</strong>
                        @endif
                    </h3>
                </div>
            </div>
        </div>
    </section>
    <section class="quiz-view">
        <div class="container">
            <div class="quiz-title d-flex justify-content-between p-0">
                <h2 class="m-0">Chapters</h2>
            <a href="{{route('subject.test.create',$subject->id)}}" class="btn btn-outline-primary">Practice Test</a>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="qustion-list">
                        @foreach ($chapters as $chapter)
                            <div class="qustion-slide active">
                                <div class="qustion-number ">{{$chapter->name}}</div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    {{-- PREVIOUS TEST RESULTS --}}
        <div class="wrapper d-flex flex-column mt-2">
            <div class="container">
                <div id="kt_wrapper">
                    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
                    <!-- begin:: Content -->
                        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

                            <div class="kt-portlet kt-portlet--mobile">
                                <div class="kt-portlet__head kt-portlet__head--lg d-flex justify-content-between mt-2">
                                    <div class="kt-portlet__head-label">
                                        <span class="kt-portlet__head-icon">
                                            <i class="kt-font-brand flaticon2-line-chart"></i>
                                        </span>
                                        <h3 class="kt-portlet__head-title mt-2">
                                            Previous Tests
                                        </h3>
                                    </div>
                                    <div class="kt-portlet__head-toolbar">
                                        <div class="kt-portlet__head-wrapper">
                                            <div class="kt-portlet__head-actions">
                                                <div class="dropdown dropdown-inline">
                                                    <button type="button" class="btn btn-default btn-icon-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="la la-download"></i> Export
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <ul class="kt-nav">
                                                            <li class="kt-nav__section kt-nav__section--first">
                                                                <span class="kt-nav__section-text">Choose an option</span>
                                                            </li>
                                                            <li class="kt-nav__item">
                                                                <a href="#" class="kt-nav__link">
                                                                    <i class="kt-nav__link-icon la la-print"></i>
                                                                    <span class="kt-nav__link-text">Print</span>
                                                                </a>
                                                            </li>
                                                            <li class="kt-nav__item">
                                                                <a href="#" class="kt-nav__link">
                                                                    <i class="kt-nav__link-icon la la-copy"></i>
                                                                    <span class="kt-nav__link-text">Copy</span>
                                                                </a>
                                                            </li>
                                                            <li class="kt-nav__item">
                                                                <a href="#" class="kt-nav__link">
                                                                    <i class="kt-nav__link-icon la la-file-excel-o"></i>
                                                                    <span class="kt-nav__link-text">Excel</span>
                                                                </a>
                                                            </li>
                                                            <li class="kt-nav__item">
                                                                <a href="#" class="kt-nav__link">
                                                                    <i class="kt-nav__link-icon la la-file-text-o"></i>
                                                                    <span class="kt-nav__link-text">CSV</span>
                                                                </a>
                                                            </li>
                                                            <li class="kt-nav__item">
                                                                <a href="#" class="kt-nav__link">
                                                                    <i class="kt-nav__link-icon la la-file-pdf-o"></i>
                                                                    <span class="kt-nav__link-text">PDF</span>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                &nbsp;
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="kt-portlet__body">

                                    <!--begin: Datatable -->
                                    <table class="table table-striped- table-bordered table-hover table-checkable" id="subject_table">
                                        <thead>
                                            <tr>
                                                <th>Chapter(s)</th>
                                                <th>Marks Obtained</th>
                                                <th>Out of</th>
                                                <th>Test Type</th>
                                                <th>Performed on</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                             {{-- @foreach ($chapters as $chapter)
                                                 <tr>
                                                    <td>{{$chapter->id}}</td>
                                                    <td>{{$chapter->name}}</td>
                                                    <td></td>
                                                </tr>
                                            @endforeach --}}
                                        </tbody>
                                    </table>

                                    <!--end: Datatable -->
                                </div>
                            </div>
                        </div>

                        <!-- end:: Content -->
                    </div>
                </div>
            </div>

            <!-- end:: Content -->
        </div>
        {{-- </div> --}}
    </section>
@endsection